#!/bin/bash
sudo su
dnf update -y
dnf install httpd -y
systemctl start httpd
systemctl enable httpd
cd /var/www/html/
wget https://labresources.whizlabs.com/92a9ca7235acf4a0ad31e9c76c42b92d/index.html
systemctl restart httpd
